---
#
# roles/docker_okletsdoit/tasks/main.yml
#

- name: create compose directory
  become: true
  file:
    path: "{{ docker_okletsdoit_docker_builds }}/okletsdoit"
    state: directory
    owner: "{{ docker_uid }}"
    group: "{{ docker_gid }}"
    mode: 0700

- name: copy docker files
  become: true
  template:
    src: "{{ item }}.j2"
    dest: "{{ docker_okletsdoit_docker_builds }}/okletsdoit/{{ item }}"
    backup: true
    owner: "{{ docker_uid }}"
    group: "{{ docker_gid }}"
    mode: 0700
  loop:
    - docker-compose.yml

- name: create config storage directory
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ docker_uid }}"
    group: "{{ docker_gid }}"
    mode: 0777
  with_items:
    - "{{ docker_okletsdoit_docker_storage }}/okletsdoit_nginx/"

- name: create nginx config file
  become: true
  copy:
    src: default.conf.template
    dest: "{{ docker_okletsdoit_docker_storage }}/okletsdoit_nginx/default.conf.template"
    backup: true
    owner: "{{ docker_uid }}"
    group: "{{ docker_gid }}"
    mode: 0644
