---
#
# roles/docker_garage/tasks/main.yml
#

- name: create compose directory
  become: true
  file:
    path: "{{ docker_garage_docker_builds }}/garage"
    state: directory
    owner: "{{ docker_uid }}"
    group: "{{ docker_gid }}"
    mode: 0700

- name: copy docker files
  become: true
  template:
    src: "{{ item }}.j2"
    dest: "{{ docker_garage_docker_builds }}/garage/{{ item }}"
    backup: true
    owner: "{{ docker_uid }}"
    group: "{{ docker_gid }}"
    mode: 0700
  loop:
    - docker-compose.yml

- name: create config directory
  become: true
  file:
    path: "{{ docker_garage_docker_storage }}/garage_config"
    state: directory
    owner: "{{ docker_uid }}"
    group: "{{ docker_gid }}"
    mode: 0700

- name: copy config file
  become: true
  template:
    src: garage.toml.j2
    dest: "{{ docker_garage_docker_storage }}/garage_config/garage.toml"
    backup: true
    owner: "{{ docker_uid }}"
    group: "{{ docker_gid }}"
    mode: 0600

- name: create docker network with custom subnet
  become: true
  docker_network:
    name: garage
    driver: bridge
    ipam_config:
      - subnet: 172.20.0.0/16
        gateway: 172.20.0.1
        iprange: 172.20.0.0/24
    state: present
