---
#
# roles/common/vars/main.yml
#

# vcenter_host: vcenter.daynet.ianday.me
# vcenter_username: vsphere.local\administrator
# vcenter_password: '{{ vault_vcenter_password }}'
# backup_root_path: "{{ vault_backup_root_path }}" 
# backup_mount_domain:  "{{ vault_backup_mount_domain }}" 
# backup_mount_user: "{{ vault_backup_mount_user }}" 
# backup_mount_pass: "{{ vault_backup_mount_pass }}" 
# vm_user: '{{ vault_vm_user }}'
# vm_pass: '{{ vault_vm_pass }}'
# common_domain: daynet.ianday.me
# common_domain_controller: 'dc-02.{{ common_domain }}'
# common_ntp_server: '{{ common_domain_controller }}'
# domain_join_user: '{{ vault_domain_join_user }}'
# domain_join_password: '{{ vault_domain_join_password }}'
# mount_share_domain: daynet
# domain_sudo_group: domainsudo
# common_domain_base_dn: '{{ vault_domain_base_dn }}'
# ian_user: ian
# ian_user_dn: '{{ vault_ian_user_dn }}'
# ian_domain_password: '{{ vault_ian_domain_password }}'
# ian_vnc_password: '{{ vault_ian_vnc_password }}'
# pypi_user: '{{ vault_pypi_user }}'
# pypi_password: '{{ vault_pypi_password }}'
